# Generated by Django 4.2.7 on 2023-11-25 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin",
        ),
    ]
