# Generated by Django 4.2.7 on 2023-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_remove_user_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zahtjev",
            name="vrsta_prijavitelja",
            field=models.CharField(
                choices=[
                    ("Fizicka_osoba", "Fizička osoba"),
                    ("Pravna_osoba", "Pravna osoba"),
                    ("Neprofitna_organizacija", "Neprofitna organizacija"),
                    ("Drugo", "Drugo"),
                ],
                max_length=30,
            ),
        ),
    ]
