# Generated by Django 4.2.7 on 2023-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_alter_zahtjev_vrsta_prijavitelja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zahtjev",
            name="adresa_prostora",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="files",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="freeform",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="gradska_cetvrt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="kvadratura",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="mjesni_odbor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="naziv_prostora",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="osoba_obradila",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="osoba_unijela",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="token_potvrda_maila",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zahtjev",
            name="zastupnik",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
